language: python
python:
- "2.7"

install: 
- pip install -r requirements.txt
- pip install python-coveralls
- pip install coverage

script: 
- coverage run --source=edak setup.py test
- python -m unittest discover

after_success:
- coveralls